//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Синаптик
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinaptikEntities : DbContext
    {
        public SinaptikEntities()
            : base("name=SinaptikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtoriz> Avtoriz { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Development> Development { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
        public virtual DbSet<Website_developmen> Website_developmen { get; set; }
    }
}
