//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Синаптик
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_developmen
    {
        public int Id { get; set; }
        public Nullable<int> IdSites { get; set; }
        public string Prototip { get; set; }
        public string Design { get; set; }
        public string Verstka { get; set; }
        public string Marceting { get; set; }
    
        public virtual Sites Sites { get; set; }
    }
}
